const hindiBtn = document.getElementById("hindiBtn");
const englishBtn = document.getElementById("englishBtn");
const my_name_langugae = document.getElementById("my_name_langugae");
const my_name_designation = document.getElementById("my_name_designation");
const linkedin_language = document.getElementById("linkedin_language");
const instagram_language = document.getElementById("instagram_language");
const facebook_language = document.getElementById("facebook_language");
const call_language = document.getElementById("call_language");
const whatsapp_language = document.getElementById("whatsapp_language");
const email_language = document.getElementById("email_language");
const profession_language = document.getElementById("profession_language");
const job_occupdation_language = document.getElementById("job_occupdation_language");
const designation_language = document.getElementById("designation_language");
const company_language = document.getElementById("company_language");
const company_name_language = document.getElementById("company_name_language");
const income_language = document.getElementById("income_language");
const income_value_language = document.getElementById("income_value_language");
const work_link_language = document.getElementById("work_link_language");
const profile_language = document.getElementById("profile_language");
const dob_language = document.getElementById("dob_language");
const dob_value_language = document.getElementById("dob_value_language");
const height_language = document.getElementById("height_language");
const height_value_language = document.getElementById("height_value_language");
const phone_whatsapp_language = document.getElementById("phone_whatsapp_language");
const phone_whatsapp_value_language = document.getElementById("phone_whatsapp_value_language");
const caste_language = document.getElementById("caste_language");
const caste_value_language = document.getElementById("caste_value_language");
const caste_message_language = document.getElementById("caste_message_language");
const home_town_language = document.getElementById("home_town_language");
const home_town_value_language = document.getElementById("home_town_value_language");
const social_profile_language = document.getElementById("social_profile_language");
const education_language = document.getElementById("education_language");
const university_course_language = document.getElementById("university_course_language");
const university_name_language = document.getElementById("university_name_language");
const university_year_language = document.getElementById("university_year_language");
const school_12_language = document.getElementById("school_12_language");
const school_12_name_language = document.getElementById("school_12_name_language");
const school_12_year_language = document.getElementById("school_12_year_language");
const school_10_language = document.getElementById("school_10_language");
const school_10_name_language = document.getElementById("school_10_name_language");
const school_10_year_language = document.getElementById("school_10_year_language");
const father_profile_language = document.getElementById("father_profile_language");
const father_name_language = document.getElementById("father_name_language");
const father_name_value_language = document.getElementById("father_name_value_language");
const father_gotra_language = document.getElementById("father_gotra_language");
const father_gotra_value_language = document.getElementById("father_gotra_value_language");
const father_phone_language = document.getElementById("father_phone_language");
const father_phone_value_language = document.getElementById("father_phone_value_language");
const mother_profile_language = document.getElementById("mother_profile_language");
const mother_name_language = document.getElementById("mother_name_language");
const mother_name_value_language = document.getElementById("mother_name_value_language");
const mother_gotra_language = document.getElementById("mother_gotra_language");
const mother_gotra_value_language = document.getElementById("mother_gotra_value_language");
const copyAlert = document.getElementById("copyAlert");

hindiBtn.addEventListener("click", () => {
  hindiBtn.classList.add("active");
  englishBtn.classList.remove("active");
  my_name_langugae.textContent = "हर्ष पांडे";
  my_name_designation.textContent = "सॉफ्टवेयर इंजीनियर";
  linkedin_language.textContent = "लिंक्डइन";
  instagram_language.textContent = "इंस्टाग्राम";
  facebook_language.textContent = "फेसबुक";
  call_language.textContent = "फ़ोन";
  whatsapp_language.textContent = "व्हाट्सएप";
  email_language.textContent = "ईमेल";
  profession_language.textContent = "व्यवसाय";
  job_occupdation_language.textContent = "नौकरी / व्यवसाय";
  designation_language.textContent = "सॉफ्टवेयर इंजीनियर";
  company_language.textContent = "कंपनी";
  company_name_language.textContent = "अज़ुगा (ब्रिजस्टोन कंपनी)";
  income_language.textContent = "आय";
  income_value_language.textContent = "नौकरी: 17 लाख वार्षिक + पारिवारिक व्यवसाय आय अतिरिक्त";
  work_link_language.textContent = "कार्य विस्तृत प्रोफ़ाइल";
  profile_language.textContent = "प्रोफ़ाइल";
  dob_language.textContent = "जन्म तिथि";
  dob_value_language.textContent = "23 अक्टूबर 2001";
  height_language.textContent = "ऊंचाई";
  height_value_language.textContent = "5 फीट 8 इंच";
  phone_whatsapp_language.textContent = "फ़ोन और व्हाट्सएप";
  phone_whatsapp_value_language.textContent = "7891676144";
  caste_language.textContent = "जाति";
  caste_value_language.textContent = "हिन्दू - ब्राह्मण आदि गोर";
  caste_message_language.textContent = "*जाति मेरे लिए मायने नहीं रखती, अन्य जातियों भी चलेगी";
  home_town_language.textContent = "गृह नगर / जन्म स्थान";
  home_town_value_language.textContent = "जयपुर, राजस्थान - भारत";
  social_profile_language.textContent = "सामाजिक प्रोफ़ाइल";
  education_language.textContent = "शिक्षा";
  university_course_language.textContent = "बी.टेक कंप्यूटर विज्ञान और इंजीनियरिंग";
  university_name_language.textContent = "लवली प्रोफेशनल यूनिवर्सिटी";
  university_year_language.textContent = "2019 - 2023";
  school_12_language.textContent = "बारहवीं कक्षा";
  school_12_name_language.textContent = "एमपीएस इंटरनेशनल";
  school_12_year_language.textContent = "2018 - 2019";
  school_10_language.textContent = "दसवीं कक्षा";
  school_10_name_language.textContent = "एमपीएस इंटरनेशनल";
  school_10_year_language.textContent = "2016 - 2017";
  father_profile_language.textContent = "पिता प्रोफाइल";
  father_name_language.textContent = "नाम";
  father_name_value_language.textContent = "राजेश पांडे";
  father_gotra_language.textContent = "गोत्र";
  father_gotra_value_language.textContent = "मंदाजरा";
  father_phone_language.textContent = "फ़ोन और व्हाट्सएप";
  father_phone_value_language.textContent = "9413963203";
  mother_profile_language.textContent = "माँ प्रोफ़ाइल";
  mother_name_language.textContent = "नाम";
  mother_name_value_language.textContent = "लक्ष्मी पांडे";
  mother_gotra_language.textContent = "गोत्र";
  mother_gotra_value_language.textContent = "गुबाने";
  copyAlert.textContent = "नंबर कॉपी किया गया!";
});

englishBtn.addEventListener("click", () => {
  englishBtn.classList.add("active");
  hindiBtn.classList.remove("active");
  my_name_langugae.textContent = "Harsh Pandey";
  my_name_designation.textContent = "Software Engineer";
  linkedin_language.textContent = "LinkedIn";
  instagram_language.textContent = "Instagram";
  facebook_language.textContent = "Facebook";
  call_language.textContent = "Phone";
  whatsapp_language.textContent = "WhatsApp";
  email_language.textContent = "Email";
  profession_language.textContent = "Profession";
  job_occupdation_language.textContent = "Job / Ocuupation";
  designation_language.textContent = "Software Engineer";
  company_language.textContent = "Company";
  company_name_language.textContent = "Azuga (Bridgestone Company)";
  income_language.textContent = "Job: 17 LPA + Family Business Income Extra";
  income_value_language.textContent = "Job: 17 LPA + Family Business Income Extra";
  work_link_language.textContent = "Work Detailed Profile";
  profile_language.textContent = "Profile";
  dob_language.textContent = "Date Of Birth";
  dob_value_language.textContent = "23 October 2001";
  height_language.textContent = "Height";
  height_value_language.textContent = "5 Feet 8 Inch";
  phone_whatsapp_language.textContent = "Phone & WhatsApp";
  phone_whatsapp_value_language.textContent = "7891676144";
  caste_language.textContent = "Caste";
  caste_value_language.textContent = "Hindu - Brahmin Adi Gor";
  caste_message_language.textContent = "*Caste Doesn't matter to me, open for other castes as well";
  home_town_language.textContent = "Home Town / Place Of Birth";
  home_town_value_language.textContent = "Jaipur , Rajasthan - India";
  social_profile_language.textContent = "Social Profile";
  education_language.textContent = "Education";
  university_course_language.textContent = "B.Tech Computer Science & Engineering";
  university_name_language.textContent = "Lovely Professional University";
  university_year_language.textContent = "2019 - 2023";
  school_12_language.textContent = "CLASS XII";
  school_12_name_language.textContent = "MPS International";
  school_12_year_language.textContent = "2018 - 2019";
  school_10_language.textContent = "CLASS X";
  school_10_name_language.textContent = "MPS International";
  school_10_year_language.textContent = "2016 - 2017";
  father_profile_language.textContent = "Father Profile";
  father_name_language.textContent = "Name";
  father_name_value_language.textContent = "Rajesh Pandey";
  father_gotra_language.textContent = "Gotra";
  father_gotra_value_language.textContent = "Mandajra";
  father_phone_language.textContent = "Phone & WhatsApp";
  father_phone_value_language.textContent = "9413963203";
  mother_profile_language.textContent = "Mother Profile";
  mother_name_language.textContent = "Name";
  mother_name_value_language.textContent = "Laxmi Pandey";
  mother_gotra_language.textContent = "Gotra";
  mother_gotra_value_language.textContent = "Gubane";
  copyAlert.textContent = "Number copied!";
});


function copyToClipboard(elementId) {
    const text = document.getElementById(elementId).innerText;
    navigator.clipboard.writeText(text).then(() => {
      showCopyAlert();
    }).catch(err => {
      console.error('Failed to copy!', err);
    });
}

function showCopyAlert() {
    const alertBox = document.getElementById("copyAlert");
    alertBox.classList.add("show");

    setTimeout(() => {
        alertBox.classList.remove("show");
    }, 5000);
}
